List<String> categoryList = [
  'Accessories',
  'Appliances',
  'Automotive',
  'Baby',
  'Bakery',
  'Bath & Body',
  'Beer, Wine & Liquor',
  'Beverages',
  'Bicycle Gear',
  'Bird Supplies',
  'Bread',
  'Breakfast & Cereal',
  'Camping Gear',
  'Candy',
  'Canned Goods & Soup',
  'Cat Supplies',
  'Cleaning & Household',
  'Clothing',
  'Cosmetics',
  'Dairy, Eggs & Cheese',
  'Deli',
  'Diet Foods',
  'Dog Supplies',
  'Electronics',
  'Exercise & Fitness',
  'First Aid',
  'Fish Supplies',
  'Fragrances',
  'Frozen Foods',
  'Fruits & Vegetables',
  'Furniture',
  'Grains, Pasta & Sides',
  'Grocery',
  'Hair Care',
  'Home & Patio',
  'Home Improvement',
  'Juice',
  'Kosher',
  'Meat',
  'Medicine',
  'Nutrition & Weight Loss',
  'Oral Care',
  'Organic',
  'Other',
  'Paper Goods',
  'Party Accessories',
  'Personal Care',
  'Pet Care',
  'Pools & Accessories',
  'School & Office Supplies',
  'Seafood',
  'Shoes',
  'Skin Care',
  'Small Animal Supplies',
  'Snacks',
  'Spices & Baking',
  'Sports & Outdoors',
  'Tobacco',
  'Toys',
  'Vitamins & Supplements',
];

List<String> weightUnitsList = [
  'Grams',
  'Kilograms',
  'Milligrams',
  'Ounces',
  'Pounds',
];

List<String> volumeUnitsList = [
  'Liters',
  'Milliliters',
  'Cubic Meters',
  'Cubic Feet',
];
